spring:
  application:
    name: furnidream
  datasource:
    url: jdbc:mysql://ssg-java3.iptime.org:3306/furnidb
    username: furni
    password: furni
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      max-lifetime: 60000
      minimum-idle: 5
      idle-timeout: 30000
      auto-commit: false
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    root: info
    com.furnycrew: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.furnycrew.furnidream
  mapper-locations: classpath*:mappers/**/*-mapper.xml

server:
  servlet:
    context-path: /app
    session:
      tracking-modes: cookie

ftp:
  server:
    host: ssg-java3.iptime.org
    port: 21
    username: furni
    password: furni